name: Flutter action

on:
  push:
    branches:
      - main

jobs:
  lint_shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Cache Java dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-java-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-java-

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - run: flutter pub get

      - run: flutter build apk --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          token: ${{ secrets.TOKEN_TEST }}
          tag: v1.0.${{ github.run_number }}
      
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@v0.3
        with :
          folder_id: ${{ secrets.FOLDER_ID }}
          file: "build/app/outputs/apk/release/*"
          token: ${{ secrets.CREDENTIALS }}
          filename: "app-release.apk"
